Repository pimcore/advanced-object-search, pull requests merged in 2020-12, with the labels that each got.

#98 Add overflow scroller for secondary tbar
  src/Resources/public/js/searchConfig/resultPanel.js
Labels: enhancement

#99 Remove from queue if object no longer exists
  src/Service.php
Labels: bug

#101 added process urls - batch and export for grid panel.
  src/Resources/public/js/searchConfig/resultAbstractPanel.js
  src/Resources/public/js/searchConfig/resultPanel.js
Labels: bug

#104 Elasticsearch 7 compatibility
  README.md
  composer.json
  src/Service.php
Labels: Improvement
