Repository pimcore/advanced-object-search, pull requests merged in 2022-12, with the labels that each got.

#169 Replace plugins with event listener
  doc/01_Extending_Filters.md
  src/AdvancedObjectSearchBundle.php
  src/Resources/public/js/events.js
  src/Resources/public/js/searchConfig/resultPanel.js
  src/Resources/public/js/startup.js
Labels: Bug

#176 Added ES8 support
  README.md
  composer.json
  src/AdvancedObjectSearchBundle.php
  src/DependencyInjection/AdvancedObjectSearchExtension.php
  src/DependencyInjection/Configuration.php
  src/Resources/config/services.yml
  src/Service.php
  src/Tools/ElasticSearchConfigService.php
  src/Tools/EsClientFactory.php
Labels: BC-BREAK, Task

#194 Remove `o_` prefixes
  src/Controller/AdminController.php
  src/Installer.php
  src/Migrations/Version20221130130306.php
  src/Resources/config/pimcore/config.yml
  src/Service.php
Labels: Task
