Repository pimcore/advanced-object-search, pull requests merged in 2025-03, with the labels that each got.

#287 [Task]: PhpStan: Add strict mode check
  composer.json
  phpstan.neon
  src/Command/ProcessUpdateQueueCommand.php
  src/Command/ReindexCommand.php
  src/Command/ServiceAwareCommand.php
  src/Command/UpdateMappingCommand.php
  src/Controller/AdminController.php
  src/DependencyInjection/AdvancedObjectSearchExtension.php
  src/DependencyInjection/Configuration.php
  src/Event/AbstractFilterListener.php
  src/Event/AdvancedObjectSearchEvents.php
  src/Event/FilterListingEvent.php
  src/Event/FilterSearchEvent.php
  src/Event/SavedSearchEvent.php
  src/Event/SavedSearchEvents.php
  src/EventListener/IndexUpdateListener.php
  src/Filter/FieldDefinitionAdapter/AdvancedManyToManyObjectRelation.php
  src/Filter/FieldDefinitionAdapter/AdvancedManyToManyRelation.php
  src/Filter/FieldDefinitionAdapter/CalculatedValue.php
  src/Filter/FieldDefinitionAdapter/Checkbox.php
  src/Filter/FieldDefinitionAdapter/Country.php
  src/Filter/FieldDefinitionAdapter/Countrymultiselect.php
  src/Filter/FieldDefinitionAdapter/Date.php
  src/Filter/FieldDefinitionAdapter/Datetime.php
  src/Filter/FieldDefinitionAdapter/DefaultAdapter.php
  src/Filter/FieldDefinitionAdapter/FieldDefinitionAdapterInterface.php
  src/Filter/FieldDefinitionAdapter/Fieldcollections.php
  src/Filter/FieldDefinitionAdapter/Language.php
  src/Filter/FieldDefinitionAdapter/Languagemultiselect.php
  src/Filter/FieldDefinitionAdapter/Localizedfields.php
  src/Filter/FieldDefinitionAdapter/ManyToManyObjectRelation.php
  src/Filter/FieldDefinitionAdapter/ManyToManyRelation.php
  src/Filter/FieldDefinitionAdapter/ManyToOneRelation.php
  src/Filter/FieldDefinitionAdapter/Multiselect.php
  src/Filter/FieldDefinitionAdapter/Numeric.php
  src/Filter/FieldDefinitionAdapter/Objectbricks.php
  src/Filter/FieldDefinitionAdapter/QuantityValue.php
  src/Filter/FieldDefinitionAdapter/Select.php
  src/Filter/FieldDefinitionAdapter/Table.php
  src/Filter/FieldDefinitionAdapter/Time.php
  src/Filter/FieldDefinitionAdapter/User.php
  src/Filter/FieldSelectionInformation.php
  src/Filter/FilterEntry.php
  src/Installer.php
  src/Maintenance/UpdateQueueProcessor.php
  src/Messenger/QueueHandler.php
  src/Messenger/QueueMessage.php
  src/Migrations/PimcoreX/Version20210305134111.php
  src/Migrations/Version20191218105114.php
  src/Migrations/Version20210305134111.php
  src/Model/SavedSearch.php
  src/Model/SavedSearch/Dao.php
  src/Model/SavedSearch/Listing.php
  src/Model/SavedSearch/Listing/Dao.php
  src/Service.php
  src/Tools/IndexConfigService.php
Labels: Task, Pimcore:ToDo

#281 Add validation to check if object exists before deleting it from index
  src/Service.php
Labels: Pimcore:ToDo

#278 [Improvement]: Add on row context menu event
  src/Resources/public/js/events.js
  src/Resources/public/js/searchConfig/resultPanel.js
Labels: Pimcore:ToDo

#289 Change to attributes
  src/Controller/AdminController.php
Labels: Pimcore:ToDo

#290 [Improvement]: Add support to DBAL v4
  composer.json
  doc/03_Upgrade_Notes.md
  src/Installer.php
Labels: Improvement, Pimcore:Priority
